### ISSUE TITLE
Suggestion: meta-methods

### ISSUE THREAD

**Issue by cooljeanius** [tif-calin/votevote#8]
Basically, I'm thinking of a method that says that the winner is the candidate who wins under the most other methods already listed (not sure if there's already a name for this?)

**Comment by tif-calin** [comment]
@cooljeanius Ah maybe you'd like the update I'm gonna release today: 
![image](https://github.com/tif-calin/votevote/assets/76538249/c4d35d1a-0c51-445b-9b32-3278acbe71ec)

Essentially it shows you which candidate wins across the most methods

**Comment by tif-calin** [comment]
@cooljeanius sorry I was missing in action for so long. I'm glad you're excited about this. I have friends who own the domain `votevote.vote` and we were talking about creating a service that allows anyone to host a vote and choose the voting method.

One easter egg we talked about was adding a system where every voter can also choose which voting system they'd prefer their vote be counted in. So basically if 18% of people choose `Black's Method` and 42% choose `Borda Count` and 40% choose `STV` then the winner by Black's Method gets 0.18 points, the winner by Borda Count method gets 0.42 points, and the winner by STV gets 0.4 points.

What do you think?

**Comment by cooljeanius** [comment]
> @cooljeanius sorry I was missing in action for so long. I'm glad you're excited about this. I have friends who own the domain `votevote.vote` and we were talking about creating a service that allows anyone to host a vote and choose the voting method.
> 
> One easter egg we talked about was adding a system where every voter can also choose which voting system they'd prefer their vote be counted in. So basically if 18% of people choose `Black's Method` and 42% choose `Borda Count` and 40% choose `STV` then the winner by Black's Method gets 0.18 points, the winner by Borda Count method gets 0.42 points, and the winner by STV gets 0.4 points.
> 
> What do you think?

Yeah, that sounds interesting! Of course, you could get even further meta with applying different voting methods to the votes for voting methods, but there's got to be a recursion limit somewhere... `:-P`

**Comment by tif-calin** [comment]
That'd be like having a vote for what the best voting method is. Which ever voting method wins has the election recomputed through that method. And then again. And again. I wonder if it'd reach an asymptote eventually

Anyways, I don't plan on implementing any "meta" methods as proper systems themselves. I like them to be idempotent and [pure](https://en.wikipedia.org/wiki/Pure_function). That's why I don't include probabilistic methods or gimmicky methods like the ones where candidates negotiate amongst themselves. 

However, I do plan on expanding the "stat box" thing to give you more of a "meta _analysis_". If you have any ideas for ways this can be done, feel free to reopen this issue or make a new one. Some basic ideas I have include:
* show strong/weak condorcet winners
* make it easy to see which methods exactly a candidate wins under
* categorical groupings of methods. E.g. "candidate `blue` wins 92% of `condorcet` methods" or "candidate `red` wins 77% of `cardinal` methods"
